// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3DajtTROg5zNUJAAiJGpdrsvoWMa6kVY',
    appId: '1:751603295081:web:66299b67514148c7c093f8',
    messagingSenderId: '751603295081',
    projectId: 'apps-1e05f',
    authDomain: 'apps-1e05f.firebaseapp.com',
    storageBucket: 'apps-1e05f.appspot.com',
    measurementId: 'G-601GNQ08ZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjn12HsrljCO7g2n-B4Pv8QucvimEw42s',
    appId: '1:751603295081:android:348bf7b3f88ecdf2c093f8',
    messagingSenderId: '751603295081',
    projectId: 'apps-1e05f',
    storageBucket: 'apps-1e05f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRWzLDmTAwa02XktZW0ly1yEzqZp_sGRs',
    appId: '1:751603295081:ios:905759b0ee672182c093f8',
    messagingSenderId: '751603295081',
    projectId: 'apps-1e05f',
    storageBucket: 'apps-1e05f.appspot.com',
    iosBundleId: 'com.example.designcredits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRWzLDmTAwa02XktZW0ly1yEzqZp_sGRs',
    appId: '1:751603295081:ios:905759b0ee672182c093f8',
    messagingSenderId: '751603295081',
    projectId: 'apps-1e05f',
    storageBucket: 'apps-1e05f.appspot.com',
    iosBundleId: 'com.example.designcredits',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3DajtTROg5zNUJAAiJGpdrsvoWMa6kVY',
    appId: '1:751603295081:web:d97aecd55e50d4b1c093f8',
    messagingSenderId: '751603295081',
    projectId: 'apps-1e05f',
    authDomain: 'apps-1e05f.firebaseapp.com',
    storageBucket: 'apps-1e05f.appspot.com',
    measurementId: 'G-R0Y8YJVPY1',
  );
}
